version: '3.8'
    # Mapeo de dispositivos de hardware para la Raspberry Pi
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"  # Arduino
      - "/dev/video0:/dev/video0"    # Cámara 0 (Captura)
      - "/dev/video1:/dev/video1"    # Cámara 0 (Metadatos)
      - "/dev/video2:/dev/video2"    # Cámara 2 (Captura)
      - "/dev/video3:/dev/video3"    # Cámara 2 (Metadatos)

volumes:
  db_data:
  certbot_conf:
  certbot_www:
