name: Deploy en Raspberry Pi

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Actualizar código
        run: |
          cd ~/Proyecto-Final-ASIR
          git pull origin main

      - name: Detener contenedores (Liberar puerto serie)
        run: |
          cd ~/Proyecto-Final-ASIR
          docker compose down || true

      - name: Actualizar Arduino
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          cd ~/Proyecto-Final-ASIR/aplicacion-parking/servo_and_lcd_serial
          
          # Asegurarse de tener el core y librerías instaladas
          arduino-cli core install arduino:avr
          arduino-cli lib install "LiquidCrystal I2C"
          arduino-cli lib install "Servo"
          
          # Compilar y subir al Arduino (Asumiendo Arduino Uno en /dev/ttyACM0)
          arduino-cli compile --fqbn arduino:avr:uno servo_and_lcd_serial.ino
          arduino-cli upload -p /dev/ttyACM0 --fqbn arduino:avr:uno servo_and_lcd_serial.ino

      - name: Redesplegar contenedores
        run: |
          cd ~/Proyecto-Final-ASIR
          docker compose up --build -d
          docker compose ps